name: Build to GHCR and Deploy to Railway

on:
  push:
    branches:
      - main # သင့် branch အမည် main အတိုင်း ထားပါတယ်

jobs:
  build-and-push-ghcr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # GHCR အတွက် အသုံးပြုသူအမည်နှင့် repository အမည်ကို စာလုံးသေးအမှန်အတိုင်း သတ်မှတ်ပေးထားခြင်း
          tags: |
            ghcr.io/zawmoewin120298-collab/nova-proxyweb:latest
            ghcr.io/zawmoewin120298-collab/nova-proxyweb:v1.0.2

  deploy-to-railway:
    needs: build-and-push-ghcr
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Deploy to Railway
        run: railway up --detach
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
